### ISSUE TITLE
Fix the issue of `GetLastBatch` in the state module

### ISSUE THREAD

**Issue by cool-develope** [0xPolygonHermez/zkevm-node#1022]
We are getting the error with `index out of range [0] with length 0` in `GetLastBatch`.

**Comment by arnaubennassar** [comment]
Can you describe the context? When this is happening? Where are you running the code that trigger the error?

**Comment by cool-develope** [comment]
When running `test/e2e/ethtransfer_test.go`, it is trying to get the last batch from empty state
