### ISSUE TITLE
The main_exit_root of L2 is not being updated 

### ISSUE THREAD

**Issue by cool-develope** [0xPolygonHermez/zkevm-node#1026]
Let's assume we have only L1 deposits, to claim it in L2 we need to update the main_exit_root in L2,  but the sequencer only updates it when have L2 txs with batch.
I suggest make an empty batch to update the L2 main_exit_root in the sequencer.

**Comment by arnaubennassar** [comment]
This should be fixed by #1028 . Can you checkout that branch and test that it actually fixes the problem @cool-develope ?
