### ISSUE TITLE
Pull access denied for hermeznetwork/geth-zkevm-contracts

### ISSUE THREAD

**Issue by lepar** [0xPolygonHermez/zkevm-node#1104]
*******Edit****** I found the issue that it's private, but that was in July 22, is there any estimate how long it'll take?

Unable to pull the zkevm contracts image from docker.

Steps to reproduce:
1. Clone repository
2. run "make run"

zkevm-db works but unable to pull the contracts on the "make run" script.

Complete error:

~/zkevm-node$ make run
docker-compose -f docker-compose.yml up -d zkevm-db
Starting zkevm-db ... done
docker-compose -f docker-compose.yml up -d zkevm-mock-l1-network
Pulling zkevm-mock-l1-network (hermeznetwork/geth-zkevm-contracts@sha256:7ac654f8b06baaca030f0022398dca1ffaa872be07dcf03c6bbc3ff6011adb88)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling zkevm-mock-l1-network (hermeznetwork/geth-zkevm-contracts@sha256:7ac654f8b06baaca030f0022398dca1ffaa872be07dcf03c6bbc3ff6011adb88)...
ERROR: pull access denied for hermeznetwork/geth-zkevm-contracts, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:218: run] Error 1

**Comment by arnaubennassar** [comment]
We're currently working on integrating all the pieces. Once everything is working we will open the Docker images as well as update documentation for running locally and on "production".

It shouldn't be more than a few weeks until we got there. If you don't mind I'll close this issue in favor of #909 as updating the docs will include for sure the release of the containers.

In the meantime, if you really want to test this, you can manually build the containers yourself, as all the code is open sourced in the repos of the organization. But be aware that it won't be easy, and things are quite unstable right now
