### ISSUE TITLE
`out of gas` in sequence batch

### ISSUE THREAD

**Issue by cool-develope** [0xPolygonHermez/zkevm-node#1118]
When we try to execute both `SequenceBatches` and `VerifyBatch` in one block, we are getting `out of gas` error in `SequenceBatches`.
It's related to storage changes in smart contract side, especially matic transfer.
We need to add 20K gas to the original gas estimation to avoid this situation.

**Comment by ToniRamirezM** [comment]
This has already been fixed in the current eth tx manager.
