### ISSUE TITLE
The GER is missing in the trusted state.

### ISSUE THREAD

**Issue by cool-develope** [0xPolygonHermez/zkevm-node#1264]
We found the edge case of issue in `updateGerInBatch`.
```cmd
Batch 1     -----> root 0
    Deposit 1   -> root 1 in L1
--------------------------------> root 0 in L2

Batch 2     -----> root 1
    Deposit 2   -> root 2 -> updateGerInBatch
--------------------------------> UI requires Claim
    Claim 1     -> root 1
--------------------------------> root 1 in L2
```
Batch 2 is the current open batch, we have `updateGerInBatch`, after that we have a claim tx in the bridge side, but bridge is not fully synchronizing the `root 2` so it generates merkle proof based on `root 1`. When execute this claim tx in the node, then we face the error of `root 1` is not stored because we already have `root 2` in the open batch.

**Comment by arnaubennassar** [comment]
Current idea to fix the situation: each time a new GER is detected, the sequencer will close the current batch and open a new one with the latest GER. Note that this includes a situation where a batch has no txs (currently in this scenario the batch is being updated with the new GER)

**Comment by Mikelle** [comment]
This issue can be closed, bcs other issue was implemented - https://github.com/0xPolygonHermez/zkevm-node/issues/1299
