### ISSUE TITLE
Better handling for sending L1 txs

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#1271]
Instead of sending txs synchronously from multiple points of the code (sequencer and aggregator), store the txs that need to be sent on a DB, and have an additional component that deals with sending those txs.

This should enable:

- Better security (only one component needs the private key)
- More resilient: components can go down, but the new component still keeps track of pending txs
- Better nonce management: on the DB we can store what nonce is used for each tx. If facing a mismatched nonce this could even be edited manually by the admins

**Comment by tclemos** [comment]
Centralizing everything in a single component can lead us to different problems, for example:
- this new component will not work running alone
- sequencer and aggregator will not "work" without this component(they can work persisting to the db, but they will not affect the rollup)
- in case the user wants to run both, sequencer and aggregator and we want to allow two different accounts to provide the funds to send sequencer and to send proofs, we should refactor the code to allow more than one Keystore to be provided.

My suggestion is that we keep the current components, sequencer and aggregator, and do a revamp on the integration between sequencer, aggregator, and ethtxmanager to use a DB to store the sequence/proof data before sending it to L1, allowing the data on the DB to be the source of truth when sending the senquences/proofs to L1.

With that, we can continue to use the current implementation to have different keys for the sequencer and aggregator if needed and also, make it easier to run a sequencer or aggregator instance, without having to require to instantiate more components.
