### ISSUE TITLE
Cannot initialize L2 network 

### ISSUE THREAD

**Issue by hyemmie** [0xPolygonHermez/zkevm-node#1302]
from current commit `936d7dd do not restart on error`, initializing network is unavailable
cuz `init-network script from Makefile`, `script/init_network/main.go` and `tools/network.go` are commented out

and the `running_local` docs have this warning
> WARNING: This documentation is outdated, it will be updated soon

is `init_network` currently testing now? if so, when will the feature be completed?

**Comment by arnaubennassar** [comment]
Yes, `init-network` is deprecated. We're working on updating the running local docs: https://github.com/0xPolygonHermez/zkevm-node/pull/1347

**Comment by arnaubennassar** [comment]
Hi @hyemmie , we've updated the docs and this shouldn't be a problem, so I'll close the issue. Feel free to re-open it if you're still facing problems.
