### ISSUE TITLE
Got unexpected TPS test result!

### ISSUE THREAD

**Issue by KwonMinho** [0xPolygonHermez/zkevm-node#1490]
Hi!

I'm a developer learning polygon zkevm (..deep dive)

I built a zkevm node in the local environment and ran the TPS test.

I was expecting around 50 TPS > (The transaction is related to a simple transfer)

The reason why I expected 50 TPS(instead of 1000 ~ 2000 TPS) is because I ran components(expect zkEVM prover) of the zkEVM node in the `Raspberry Pi 4` environment.

However, I got 3~4 TPS results.
![image](https://user-images.githubusercontent.com/36630283/209460009-eea4cc88-90ed-4a88-b629-ccef6f640e30.png)

`I have two questions `

1.  Is the TPS test I did the right way to measure it? (If not, what should I do?)
2. To achieve 1000TPS performance, which config value should be adjusted? (Including hardware changes)

## Test Env

All components were executed in docker.
![image](https://user-images.githubusercontent.com/36630283/209459861-2813ee33-6ade-489b-bba9-b6e5802c469e.png)

## Test Method

The test tool used the `txsender` script (in /test/scripts).
```
txsender -w send 1000
```

**Comment by KwonMinho** [comment]
prover config
```json
{
    "runExecutorServer": true,
    "runExecutorClient": false,
    "runExecutorClientMultithread": false,

    "runStateDBServer": true,
    "runStateDBTest": false,

    "runAggregatorServer": false,
    "runAggregatorClient": false,
    "runAggregatorClientMock": true, 
    "aggregatorClientTimeout": 15000000,
    "aggregatorClientMockTimeout": 15000000,

    
    "runFileGenBatchProof": false,
    "runFileGenAggregatedProof": false,
    "runFileGenFinalProof": false,
    "runFileProcessBatch": false,
    "runFileProcessBatchMultithread": false,

    "runKeccakScriptGenerator": false,
    "runKeccakTest": false,
    "runStorageSMTest": false,
    "runBinarySMTest": false,
    "runMemAlignSMTest": false,
    "runSHA256Test": false,
    "runBlakeTest": false,

    "executeInParallel": true,
    "useMainExecGenerated": false,
    "saveRequestToFile": false,
    "saveInputToFile": false,
    "saveDbReadsToFile": false,
    "saveDbReadsToFileOnChange": false,
    "saveOutputToFile": true,
    "saveProofToFile": true,
    "saveResponseToFile": false,
    "loadDBToMemCache": true,
    "opcodeTracer": false,
    "logRemoteDbReads": false,
    "logExecutorServerResponses": false,

    "proverServerPort": 50051,
    "proverServerMockPort": 50052,
    "proverServerMockTimeout": 10000000,
    "proverClientPort": 50051,
    "proverClientHost": "127.0.0.1",

    "executorServerPort": 50071,
    "executorROMLineTraces": false,
    "executorClientPort": 50071,
    "executorClientHost": "172.30.1.185",

    "stateDBServerPort": 50061,
    "stateDBURL": "local",

    "aggregatorServerPort": 50081,
    "aggregatorClientPort": 50081,
    "aggregatorClientHost": "172.30.1.188",

    "mapConstPolsFile": false,
    "mapConstantsTreeFile": false,

    "inputFile": "input_executor_0.json",
    "inputFile2": "input_executor_1.json",

    "rom": "config/scripts/rom.json",
    "keccakScriptFile": "config/scripts/keccak_script.json",
    "storageRomFile": "config/scripts/storage_sm_rom.json",

    "outputPath": "output",

    "databaseURL": "postgresql://prover_user:prover_pass@172.30.1.188:5432/prover_db",
    "dbNodesTableName": "state.nodes",
    "dbProgramTableName": "state.program",
    "dbAsyncWrite": false,
    "cleanerPollingPeriod": 600,
    "requestsPersistence": 3600,
    "maxExecutorThreads": 20,
    "maxProverThreads": 8,
    "maxStateDBThreads": 8
}
```

**Comment by arnaubennassar** [comment]
we're working on sequencer improvements to increase the throughput. Right now the sequencer is the bottleneck...
but you shouldn't expect 1000 TPS any time soon. It's going to be a progressive improvement, and we will ship updates that will make things way faster soon, but 1000 TPS it's goping to take time to get there.

Closing the issue, since there is no action point that you can take from here. Just wait for new releases

**Comment by KwonMinho** [comment]
Thank you very much for your response..

Thanks to your information, many doubts have been cleared.

I repect the polygon zkevm team for always working hard.
