### ISSUE TITLE
Differentiate the jRPC endpoint is being called when adding the prometheus metric

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#1500]
it will also be very nice to capture:
- the response time
- OK/KO

**Comment by tclemos** [comment]
I've talked to @arnaubennassar and @xavier-romero about this issue and it's obsolete when compared to the tools we already have deployed to monitor the endpoints.

The idea was to monitor the jRPC request with the possibility to identify the method provided in the request, and we already have a tool that allows us to monitor individual methods.
