### ISSUE TITLE
Review logs to use `%v` and `%w` correctly

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#1518]
When we log errors using `%w` but the error is actually not wrapped to contain the trace, the error message is actually not logged. A pattern that we could use is to:

- Always log the error with `%v` at the deepest point in the stack (when it's generated), and wrap it here
- Log again in the highest point in the stack using `%w`

**Comment by tclemos** [comment]
I think there is a misunderstanding here.

We don't have to wrap errors when logging, we need to wrap when returning it.

We must never use %w for logs
We must always use %v for returning errors
