### ISSUE TITLE
Improve debug table behaviour

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#1605]
- Add a label to understand what component is logging the error (sequencer, sync, ...)
- Encode byte arrays in hexa instead of base 64 (default conversion done by Go)
- capture the executor top level error, not only the request
- capture requests also when something unexpected happens even if there is not a top level error from the executor (for instance an error on the RLP or tx hash decoding)

**Comment by ToniRamirezM** [comment]
```
CREATE TYPE level_t AS ENUM ('0', '1', '2', '3', '4', '5', '6', '7');

CREATE TABLE events (
   id BIGSERIAL PRIMARY KEY,
   received_at timestamp WITH TIME ZONE default CURRENT_TIMESTAMP,
   ip_address inet,
   source varchar(32) not null,
   component varchar(32),
   level level_t not null,
   eventid varchar(32) not null,
   description text,
   data bytea,
   json jsonb
);
```

- Also log the information stored
- Configuration optional, if exists we store in db, if not we only log
- log startup events of the node
