### ISSUE TITLE
rawtx in genesis.json file

### ISSUE THREAD

**Issue by bradyjoestar** [0xPolygonHermez/zkevm-node#1611]
I am looking at the code of `zkevm-node`.

In the genesis file, I see that there is a transaction field. May I ask how the rawtx is generated here? Is there any special tool for it? thanks.

**Comment by invocamanman** [comment]
Yes, there are one generator file and one tool for it:
The genesis-gen is the generator file: https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/deployment/genesis-gen.json
The tool that reads the genesiss-gen and generate the genesis with all the transactions is here: https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/src/create-genesis.js

**Comment by arnaubennassar** [comment]
Closing the issue as I understand that the doubt is solved. Feel free to re-open if you've further questions @bradyjoestar

**Comment by bradyjoestar** [comment]
Sorry, I still have a little problem. lol
 
The genesis.json‘s rawtx field I saw in the zkevm-node project contains receipt information, but the genesis.json generated by tools in the zkevm-contracts project has no relevant content. 

https://github.com/0xPolygonHermez/zkevm-node/blob/966544d3f8cc117939ee8fb9cf5d0c134d5333a9/config/environments/local/local.genesis.config.json#L42

https://github.com/0xPolygonHermez/zkevm-contracts/blob/0ec16592d5d1292b1a849e10321a968df3be433a/deployment/genesis.json#L34

so what is the difference between them? thank you for. your help.
