### ISSUE TITLE
The data availability layer of polygon zkevm.

### ISSUE THREAD

**Issue by guoshijiang** [0xPolygonHermez/zkevm-node#1629]
I see our project is currently rolling up transactions into the PolygonZkEVM contract. It seems that it is only rolled up, and there is no other use. Is this using ethereum as our data availability layer?

**Comment by arnaubennassar** [comment]
Yes, data availability is stored on Ethereum. Transactions are sequenced and send to Ethereum and later on those transactions are proved using ZK

**Comment by guoshijiang** [comment]
> Yes, data availability is stored on Ethereum. Transactions are sequenced and send to Ethereum and later on those transactions are proved using ZK

But when I look at the zk proof, it does not take the transaction data from layer1 to prove it, but takes the data from layer2 to prove it to zk-prover, and then writes the state back to layer1 after the proof is completed. It is reasonable that the data does not need to be rolled up to the first layer. Is it feasible, or do we have other mechanisms to use this data
