### ISSUE TITLE
seqenece does not seem to store transaction data

### ISSUE THREAD

**Issue by guoshijiang** [0xPolygonHermez/zkevm-node#1632]
Our seqenece does not seem to store transaction data. The transaction data is stored by L1. After the transaction is certified, the Synchronizer will synchronize to db and provide it to third-party services such as wallets and dex through RPC. Is this right?

**Comment by guoshijiang** [comment]
And it seems that our json-rpc interface writes transactions to txpool when writing, and reads statedb when reading, is this right?

**Comment by arnaubennassar** [comment]
Right now there is only one sequencer aka `trusted sequencer`, which is run by us. Other RPC instances essentially forward transactions to the trusted sequencer. The trusted sequence will send the batches to L1, and then all the other nodes can synchronise from L1.

You can experiment how the trusted sequencer works by [running local](https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/running_local.md).

In the very near future, anyone will be able to send batches to L1, by calling the smart contract, although it will take a bit of time for us to have tooling to do such thing.

Hope I've answered all your questions, feel free to re-open the issue if you've more questions
