### ISSUE TITLE
Create RPC endpoint to get gas price per tx

### ISSUE THREAD

**Issue by ToniRamirezM** [0xPolygonHermez/zkevm-node#1763]
We need to implement a new gas price estimation strategy, which is defined as follows:

### Pre-execution of Transactions

- Carry out transaction pre-execution
- Acquire the Zero-Knowledge (ZK) Counters and Used Gas Price
- Do not use ZKCounters in the calculation formula
- Include an additional field in the transaction (RLP)

### Formula for Calculation (In Pool)

- TotalTxPrice = GasUsed * L2MinGasPrice + DataLengthInBytes * byteGasCost * L1GasPrice
- BreakEvenGasPrice = TotalTxPrice / GasUsed * marginFactor
(The sequencer is to use the lower value among regular GasPrice and BreakEvenGasPrice.)

- Store breakEvenGasPrice in the pool transactions table
- L2MinGasPrice = Configuration parameter % L1 Gas price
- byteGasCost = 16 (gas per byte in the storage)
- MarginFactor: configurable constant = 1.1
- Guarantee this price for 30 seconds
  - Store the estimation for the tx hash
  - Consider this in the RPC when a new tx is added
  - If it is ‘>=’ to the estimation, accept it
  - If tx hash is not in the table, use the “5 minutes” gas price (current implementation)

### Transaction Execution (in Sequencer)

- Execute transaction using the BreakEvenGasPrice and recalculate TotalTxPrice using the actual GasUsed. Use this information to recalculate the BreakEvenGasPrice and compare it with the estimated BreakEvenGasPrice in the pre-execution
- If the difference is substantial, re-execute with the newly calculated BreakEvenGasPrice
- Log an event if a re-execution occurs
- Update ZkCounters

### Attack Protection

- After the second execution, compare again the execution and if there is still a large difference, log an event
- Possibly keep the most expensive execution. (We have to decide what to do, for the moment, do nothing, just log the event)

### BatchL2Data

- Old Format
  - RLP(tx) # r # s # v
- New Format
  - RLP(tx) # r # s # v # effectivePercentage
  - effectivePercentage = 1 byte
  - effectiveGasPrice = Floor(gasPrice * (effectivePercentage + 1) / 256)
  - The protocol team will provide the final formula to calculate effectivePercentage

### Sequencer

- Add effectivePercentage to the batchl2data when sending txs to the executor
- func calcEffectivePercentage (gasPrice, breakevenGasPrice) returns effectivePercentage

**Comment by Psykepro** [comment]
https://hackmd.io/7m6an5jtRqGAaObt4EIJOw
