### ISSUE TITLE
[Fatal bug] Tx was failed but storage was changed

### ISSUE THREAD

**Issue by graykode** [0xPolygonHermez/zkevm-node#1808]
I noticed that some transactions on your chain failed with a "reverted" error, yet their associated tokens were still transferred. This seems like a critical bug in your system.

- https://explorer.public.zkevm-test.net/tx/0xbf0baaad4d57a6ea918eab09bc1b5fd88632a5f8414caa50150b2013f2a2c7d5
- https://explorer.public.zkevm-test.net/tx/0xd7c466f9040a3ed1d956b87f28e71c39fa487213753cee44504a99ad3c2441e8

**Comment by rohanvinayak10** [comment]
I have make a tred of clob but not receive it plz help

**Comment by rohanvinayak10** [comment]
0x8C73935C7f7FfE28736e6358BAd688C4e2FeF0fb


Plz send my clob 🥺

**Comment by penpinz** [comment]
Can we update on this?

**Comment by cg-polygon** [comment]
Source code is https://github.com/clober-dex/core .
The failed transaction was an ERC20 transfer:
`// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract Clob is ERC20 {
    constructor(uint256 totalSupply_) ERC20("Clober", "CLOB") {
        _mint(msg.sender, totalSupply_ * 10**18);
    } 
}`

**Comment by ignasirv** [comment]
Yes, its a standard ERC20, is what I guessed. The balances are the ones I said, now that we have an implementation with etherscan can be seen more clearly.
https://testnet-zkevm.polygonscan.com/token/0x43d614b1ba4ba469faeaa4557aeafdec039b8795?a=0xb11AB19aD4CEab01C2b3A085349c824b52132828

**Comment by noornr** [comment]
Has the problem finally been solved?
Error Problem Fixed OR Not ?

**Comment by noornr** [comment]
> Yes, its a standard ERC20, is what I guessed. The balances are the ones I said, now that we have an integration with etherscan can be seen more clearly. https://testnet-zkevm.polygonscan.com/token/0x43d614b1ba4ba469faeaa4557aeafdec039b8795?a=0xb11AB19aD4CEab01C2b3A085349c824b52132828

Finally Error  Problem Solve Or Not Sir ?

**Comment by ignasirv** [comment]
There is no error. The tx reverted because the account doesn't have enough funds to complete the transfer.
The schedule for Mainnet is the one announced in media.

**Comment by 0xgraciegrace** [comment]
hi @noornr are you in the telegram group?
