### ISSUE TITLE
Store ZKC and closing reason on batch table

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#1810]
This will help analize the behaviour of the network. Note that closing reason only applies to trusted sequencer and trusted state!!

**Comment by Psykepro** [comment]
Steps to implement:

- create migration file `000x.sql` which to add columns for each `batch constraint` and for `closing reason` to `state.batch` table
- on creating a batch initializing the column values with max batch constraints and updating on each successful tx processed the values in the columns
- on closing batch, we save the reason

**Comment by ToniRamirezM** [comment]
I would consider (we can debate):

- Use a jsonb column to store the whole ZKCounters struct
- I would go for the first approach: easier and more performant
