### ISSUE TITLE
eth_getTransactionByHash, eth_getTransactionByBlockHashAndIndex accepting invalid transaction hashes

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#1856]
for instance, `0xz` returns null

**Comment by tclemos** [comment]
seems to be already fixed:
![image](https://user-images.githubusercontent.com/1298871/225979356-bbc730fb-86bf-4fee-9810-9febf906c4dd.png)
![image](https://user-images.githubusercontent.com/1298871/225979453-b7e622e5-607d-4e56-b204-7ed29941f4e4.png)
