### ISSUE TITLE
[Fatal bug] event log was read in failed txs

### ISSUE THREAD

**Issue by graykode** [0xPolygonHermez/zkevm-node#1871]
Hi there, We are the Clober team and we hope to resume our Polygon zkevm testnet. However, we still have a concern regarding an issue where event logs were not properly read in failed transactions. Could you please check the following transaction and script?

https://explorer.public.zkevm-test.net/tx/0xca5ec141dd945c72d8db7fb6be12add20bf10ba5d91c61b236d8f9a528d39d77

```typescript
import { ethers } from 'ethers'

const provider = new ethers.providers.JsonRpcProvider(
  'https://rpc.public.zkevm-test.net',
)

const main = async () => {
  const logs = await provider.send('eth_getLogs', [
    {
      fromBlock: '4426',
      toBlock: '4426',
    },
  ])
  console.log(logs)
}

main()
```

Output:
```shell
logs : [
  {
    address: '0x9ae760d2ffc7445535e211130c445c8ec29b499a',
    topics: [
      '0x9754cddf091a07317cd2bfc6ead4610d1a7401cf0ea4176a44ab9366d4042d7d',
      '0x000000000000000000000000580de6605a74ba0d9ed346351665b992f45a6cb5',
      '0x000000000000000000000000b007fe067b7caca64359828026e629a8e0badc54'
    ],
    data: '0x00000000000000000000000000000000000000000000000000000000000059f40000000000000000000000000000000000000000000000000000000005e7aade0000000000000000000000000000000000000000000000000000000000000001',
    blockNumber: '0x114a',
    transactionHash: '0xca5ec141dd945c72d8db7fb6be12add20bf10ba5d91c61b236d8f9a528d39d77',
    transactionIndex: '0x0',
    blockHash: '0x084e10a6f6b5e8887ae16c7508973aeb4c7081df3c3b184f9cb4aa1d11b1c0a5',
    logIndex: '0x16',
    removed: false
  },
  {
    address: '0x9ae760d2ffc7445535e211130c445c8ec29b499a',
    topics: [
      '0x9754cddf091a07317cd2bfc6ead4610d1a7401cf0ea4176a44ab9366d4042d7d',
      '0x000000000000000000000000580de6605a74ba0d9ed346351665b992f45a6cb5',
      '0x000000000000000000000000b007fe067b7caca64359828026e629a8e0badc54'
    ],
    data: '0x00000000000000000000000000000000000000000000000000000000000059fe000000000000000000000000000000000000000000000000000000024e1b11620000000000000000000000000000000000000000000000000000000000000001',
    blockNumber: '0x114a',
    transactionHash: '0xca5ec141dd945c72d8db7fb6be12add20bf10ba5d91c61b236d8f9a528d39d77',
    transactionIndex: '0x0',
    blockHash: '0x084e10a6f6b5e8887ae16c7508973aeb4c7081df3c3b184f9cb4aa1d11b1c0a5',
    logIndex: '0x17',
    removed: false
  },
  {
    address: '0x43d614b1ba4ba469faeaa4557aeafdec039b8795',
    topics: [
      '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
      '0x0000000000000000000000009ae760d2ffc7445535e211130c445c8ec29b499a',
      '0x000000000000000000000000b007fe067b7caca64359828026e629a8e0badc54'
    ],
    data: '0x0000000000000000000000000000000000000000000000056a64dfd39ddcf608',
    blockNumber: '0x114a',
    transactionHash: '0xca5ec141dd945c72d8db7fb6be12add20bf10ba5d91c61b236d8f9a528d39d77',
    transactionIndex: '0x0',
    blockHash: '0x084e10a6f6b5e8887ae16c7508973aeb4c7081df3c3b184f9cb4aa1d11b1c0a5',
    logIndex: '0x18',
    removed: false
  }
]
```

**Comment by arnaubennassar** [comment]
Looks like the problem is in the logs / events. The execution is correct, however the emitted logs are not. It would be of great help if you can share the contract code or verify on the explorer. 

The fix is already done since a few days, but it requires to re-sync the network to prevent the logs from being added in the DB. We will schedule a re-sync of public testnet soon. On the other hand, if you run your own node, the problem should be gone.

Thanks for your patience, and for reporting the bug

**Comment by arnaubennassar** [comment]
Hey @graykode we believe that our initial fix is not enough to fix the problem... It improves the log situation, but there is still one log that we believe shouldn't be there. We're working towards the final solution, and we hope to have this ready in the following hours

**Comment by graykode** [comment]
@arnaubennassar May I inquire about the estimated launch date for the final solution's testnet chain?

**Comment by krlosMata** [comment]
> Hi @arnaubennassar,
> 
> Thank you for your reply. We have located the code related to [the transaction](https://explorer.public.zkevm-test.net/tx/0xca5ec141dd945c72d8db7fb6be12add20bf10ba5d91c61b236d8f9a528d39d77) you mentioned at this link: https://github.com/clober-dex/core/blob/main/contracts/MarketRouter.sol
> 
> Additionally, we are trying to verify the contract on https://testnet-zkevm.polygonscan.com/, but we are unsure of how to obtain the apiKey. Could you please provide us with instructions on how to obtain the apiKey?
> 
> Thank you.

Hi !!
Etherscan `apiKey` will be enable soon

**Comment by arnaubennassar** [comment]
Hi @graykode looks like the fix works indeed. We're scheduling the re-sync of the network for 21:30 CET. Etherscan will take a bit more to reflect the changes, but our nodes should be ready at around ~22:30 CET

**Comment by arnaubennassar** [comment]
Update: we've not been able to re-sync yet, but it should happen soon. We've been able to confirm that after syncing a node from scratch the logs are gone.

Sorry for the long wait, we're almost there
