### ISSUE TITLE
Can’t sync past blockNumber 15386

### ISSUE THREAD

**Issue by cg-polygon** [0xPolygonHermez/zkevm-node#1883]
**Current Issue**: Can’t sync past blockNumber 15386
Using zkevm-node [v0.0.3-RC23](https://github.com/0xPolygonHermez/zkevm-node/releases/tag/v0.0.3-RC23)

Getting this error in the zkevm-sync container:
```
2023-03-20T22:13:29.089Z	WARN	synchronizer/synchronizer.go:149	error syncing blocks: error: stateRoot calculated and state root verified don't match in processTrustedVerifyBatches. Processing blockNumber: 15386	{"pid": 1, "version": ""}
[github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync](http://github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync)
	/src/synchronizer/synchronizer.go:149
main.runSynchronizer
```
All zkevm docker services are starting fine (zkevm-rpc, zkevm-prover, zkevm-sync, zkevm-pool-db, zkevm-state-db)
Zkevm-prover starts and runs without any error logs.

**Comment by arnaubennassar** [comment]
Please update versions and try again
