### ISSUE TITLE
> the error is not related to `make build`, as it looks like you're running the node.

### ISSUE THREAD

**Issue by Neoblock8** [0xPolygonHermez/zkevm-node#1943]
> the error is not related to `make build`, as it looks like you're running the node.
> 
> This is the actual error:
> 
> ```
> 2023-03-22T10:04:17.944Z FATAL cmd/run.go:93 Post "http://localhost:8545/": dial tcp [::1]:8545: connect: connection refused
> ```
> 
> It looks like you are trying to run the node in a way that it expects the L1 node to be found at `http://localhost:8545`. Please provide more details of what you are trying to achieve, and what commands are you running and config files if you still need help

Trying to connect Layer1 with ZkEVM. Layer1 nodeis running in another server. But ZkEVM try to run in one server. Try to connect L! with ZkEVM

_Originally posted by @Neoblock8 in https://github.com/0xPolygonHermez/zkevm-node/issues/1904#issuecomment-1483745634_

**Comment by arnaubennassar** [comment]
Please, can you explain what are you trying to do and how?

The easiest way to change the URL of the L1 node is to add the following env var for the node: `ZKEVM_NODE_ETHERMAN_URL = "http://your.L1node.url".`

Feel free to re-open the issue if this doesn't help your problem
