### ISSUE TITLE
L1 with L2 connection

### ISSUE THREAD

**Issue by Neoblock8** [0xPolygonHermez/zkevm-node#1948]
Hi,

Trying to connect Layer1 with ZkEVM. Layer1 node is running in another server. But ZkEVM run in one server. Try to connect L1 with ZkEVM node.

Can you provide me some setup instructions?

**Comment by arnaubennassar** [comment]
The easiest way is to add the following env var for the node: `ZKEVM_NODE_ETHERMAN_URL = "http://your.L1node.url"`.

Feel free to re-open the issue if this doesn't help your problem

**Comment by Neoblock8** [comment]
> ZKEVM_NODE_ETHERMAN_URL

Where path of config file?

**Comment by arnaubennassar** [comment]
the config file is overwritten by a env vars. It could be that you're setting it as suggested [here](https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/production-setup.md#setup)?

What docker-compose file and or commands are you using to run the node?
