### ISSUE TITLE
error getting forks error on sync #rpc

### ISSUE THREAD

**Issue by nejcb1** [0xPolygonHermez/zkevm-node#1969]
I am running latest version of zkevm-node on mainnet (hermeznetwork/zkevm-node:v0.0.3-RC35). I run my on Nethermind L1 node, which is fully synced and set in "ZKEVM_NODE_ETHERMAN_URL"

After I started all containers, I checked zkevm-node container logs, which shows fatal error "**error getting forks**". Full log is below:
{"level":"info","ts":1680161165.9932919,"caller":"db/db.go:121","msg":"Found 4 migrations as expected","pid":1,"version":""}
{"level":"fatal","ts":1680161186.012807,"caller":"cmd/run.go:98","msg":"**error getting forks:** <nil>","pid":1,"version":"","stacktrace":"main.start\n\t/src/cmd/run.go:98\ngithub.com/urfave/cli/v2.(*Command).Run\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:274\ngithub.com/urfave/cli/v2.(*Command).Run\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:267\ngithub.com/urfave/cli/v2.(*App).RunContext\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:332\ngithub.com/urfave/cli/v2.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:309\nmain.main\n\t/src/cmd/main.go:140\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
{"level":"info","ts":1680161186.6425493,"caller":"cmd/run.go:401","msg":"Starting application","pid":1,"version":"","gitRevision":"","gitBranch":"","goVersion":"go1.18.10","built":"Wed, 29 Mar 2023 09:11:13 +0000","os/arch":"linux/amd64"}
{"level":"info","ts":1680161186.6555846,"caller":"db/db.go:121","msg":"Found 4 migrations as expected","pid":1,"version":""}

When I change ZKEVM_NODE_ETHERMAN_URL to Infura RPC, it works as expected, node is syncing
{"level":"info","ts":1680162047.6337924,"caller":"state/state.go:1610","msg":"new l2 blocks detected, Number 3342, Hash 0x74d1a6d3801387a6bfabd4d3a7d42dc6a80efac90c5a9eebd260dc6cb7606884","pid":1,"version":""}
{"level":"info","ts":1680162047.6342814,"caller":"state/state.go:1610","msg":"new l2 blocks detected, Number 3343, Hash 0x67fafb3839e75562686ca5f6a75672ff276d8badf08a3882299140bc87df7b24","pid":1,"version":""}
{"level":"info","ts":1680162047.6348102,"caller":"state/state.go:1610","msg":"new l2 blocks detected, Number 3344, Hash 0x2b97228bdeabe7d8c2a8323a85ed9cea88a6e0f6caea9e6c01c6a80e0c7ff9f2","pid":1,"version":""}
{"level":"info","ts":1680162047.6352952,"caller":"state/state.go:1610","msg":"new l2 blocks detected, Number 3345, Hash 0xadc80f027c1945e2ec6e0ad70086e5929e3471f45a62c246e718a6ddec520216","pid":1,"version":""}
{"level":"info","ts":1680162047.6358347,"caller":"state/state.go:1610","msg":"new l2 blocks detected, Number 3346, Hash 0x4bcbafb95211b4e6b69169583d89c37c58ca7ff46d7c1fa8b7cce5904706c19a","pid":1,"version":""}

Is there an issue with Nethermind or?

**Comment by arnaubennassar** [comment]
hey @nejcb1 thanks for your report. TBH we've only used gETH so far... It could be that your node has some problem rather than being a Nethermind thing. We've seen some issues with some gETH nodes, then switched to another node and worked perfectly find.

I will close the issue since we don't plan to use other nodes than gETH at the moment, and looks like that with gETH is working fine

**Comment by nejcb1** [comment]
Could be, that my node is somehow set in a way, which is not compatible with zkevm-node settings. 

It's just default Nethermind setting, no special customizations. I found out that also other users in Polygon's #zkevm-support chat have identical issues with other nodes. It's reported that erigon and geth works, but others not.

If anyone find out what could be wrong, please post it here

**Comment by stepollo2** [comment]
i had the same error using geth node. on my environment i fixed the issue using erigon

**Comment by 0xtakamaka** [comment]
It's seems as this is an issue with "archive" node, which "by default" is not enabled in  Nethermind and many other clients.

I have "resolved issue" using following steps:
1. used Infura to fully sync PolygonZkEVM chain from scratch;
2. switched to Nethermind after.

And now, it works without problems! :)

**Comment by 0xtakamaka** [comment]
Above post was false. It does not work!

**Comment by mrostamii** [comment]
> Perhaps if I ran my own archive node? I don't know.

@ajb No need to deploy an archive node. As mentioned [here](https://github.com/0xPolygonHermez/zkevm-node/issues/2000#issuecomment-1534469832), you just need to update the timeout configs. I updated it to 60s:
```toml
[Node.HTTPTimeouts]
ReadTimeout = 60000000000
ReadHeaderTimeout = 60000000000
WriteTimeout = 60000000000
IdleTimeout = 120000000000
```
If you're running your geth with Docker, then add the lines above in a `config.toml` file and set `--config=<path to config.toml>`.
