### ISSUE TITLE
Gas price suggestion should be proxied to trusted sequencer

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#2024]
# Rationale

- Gas price suggestion depends on config file
- Therefore each node can suggest different price
- This is misleading for users, since only the gas price suggested by trusted sequencer matters

**Comment by tclemos** [comment]
this is already implemented:

https://github.com/0xPolygonHermez/zkevm-node/blob/b3d11c8bac267ea243177ed190bd9bda74c46b08/jsonrpc/endpoints_eth.go#L160-L171
