### ISSUE TITLE
Implement tests for forced batches

### ISSUE THREAD

**Issue by ToniRamirezM** [0xPolygonHermez/zkevm-node#2025]
https://github.com/0xPolygonHermez/zkevm-testvectors/commit/d4bc01845ddc1c3fd1c06e55b11adb253414169b
to take into account:
random data has no expectedNewLeafs
genesis can have 2 different formats:
"genesis": { "address": { balance, code, nonce, storage}, "address": { ... }, ...}
"genesis": [ {address, balance, code, nonce, storage}, {address, balance, ...}, .... ]

**Comment by Psykepro** [comment]
Found out the following problem which needs to be fixed before proceeding with testing: https://github.com/orgs/0xPolygonHermez/projects/1/views/1?pane=issue&itemId=26890524
