### ISSUE TITLE
extend JSON RPC endpoints

### ISSUE THREAD

**Issue by tfius** [0xPolygonHermez/zkevm-node#2092]
# Rationale
Wehn trying to deploy my app to zkevm all contracts deployments and all went well. But using dApp with wallet started to throw errors: 
```
"error": {
    "code": -32601,
    "message": "the method eth_accounts does not exist/is not available"
  }

```
and similary  `eth_maxPriorityFeePerGas does not exist . `

Also noticed in [docs](https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/json-rpc-endpoints.md) these two are not included.

Why should this feature exist?
These two endpoints are common and useful in dapp development.

What are the use-cases?
I have app deployed on localhost, goerli, sepolia and frontend nicely changes between them. I can't use same front end as these RPC endpoints do not exists. 

# Implementation
Do you have ideas regarding the implementation of this feature? 
Gas prices and max priority fees could be retrieved from etherman for `eth_maxPriorityFeePerGas`, for `eth_accounts` I am not sure. 

Are you willing to implement this feature?
Willing, but currently unable.

**Comment by tclemos** [comment]
Hi @tfius, thanks for sharing this with us.

The eth_accounts method is used to returned accounts registered in the node, in our case the zkEVM node does not store any private key, transactions must be signed previously and sent via eth_sendRawTransaction.

Regarding the eth_maxPriorityFeePerGas, I'll open a discussion with the team to check the possibility to implement it.

**Comment by tclemos** [comment]
Hi @tfius, I'm back with information about the `eth_maxPriorityFeePerGas`

The zkEVM node doesn't support `EIP-1559` txs yet, but the support to this EIP is on our roadmap and the `eth_maxPriorityFeePerGas` endpoint will be available as soon as we add support to the EIP-1559.

At the moment I don't have an ETA for this, but for sure we will communicate it clearly when available.

These are the endpoints you can use to help setting the prices and fees for your transactions:
- `eth_gasPrice`
- `eth_estimateGas`

then you sign the transaction and send it via:
- `eth_sendRawTransaction`
