### ISSUE TITLE
Fix error handling in OOC for forced batches

### ISSUE THREAD

**Issue by ToniRamirezM** [0xPolygonHermez/zkevm-node#2099]
finalize.go line 660

```
if err != nil || !response.IsBatchProcessed {
  f.halt(ctx, fmt.Errorf("failed to process forced batch, Executor err: %w", err))
  return lastBatchNumberInState, stateRoot
}
```

In case of OOC err is nill and it is unclear in the logs

**Comment by agnusmor** [comment]
We can pass to the function f.halt the err in case err != nil or err = fmt.Errorf("OOC") (or similar) in case err = nil
