### ISSUE TITLE
The block explorer and RPC endpoint return the different hash value

### ISSUE THREAD

**Issue by jleeqn** [0xPolygonHermez/zkevm-node#2106]
#### System information
zkEVM Node version: `v0.0.8`
OS & Version: `Linux`
Network: `Mainnet`

#### Expected behaviour
The block explorer and RPC endpoint should return the `same` hash value

#### Actual behaviour
The block explorer and RPC endpoint return the `different` hash value

#### Steps to reproduce the behaviour

RPC Endpoint
```
curl https://endpoint  \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getBlockByNumber","params":["0x3F424",false],"id":1,"jsonrpc":"2.0"}' | jq '.result.hash'
```
hash: `0xa708356cc28346a6c790bb1699182a06e334a93077dfefa28c745f2e0018af87`

Block Explorer

block [#259108](https://zkevm.polygonscan.com/block/259108)
hash: `0x62912d2013a7f3901eb77bc7e7af3db1b2320803f92abf63d963e46dd96869bd`

**Comment by tclemos** [comment]
@jleeqn I'm currently investigating this issue, we have received this information from other users too.

Are you running your own node or a shared one? If it's a shared one, could you please share the URL so we can check the data?

I've checked our public endpoint and the block hash seems to match:

```bash
curl https://zkevm-rpc.com  \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getBlockByNumber","params":["0x3F424",false],"id":1,"jsonrpc":"2.0"}'
```
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "parentHash": "0xd353acd5239f1901487364e9a387fe7e6576b251bd4b8fcbaceddbcc27a846d6",
        "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
        "miner": "0x148ee7daf16574cd020afa34cc658f8f3fbd2800",
        "stateRoot": "0x7f63aa83489eb98b234dfb8f15f929d6f2d80834ba7359975259c6739cac8d31",
        "transactionsRoot": "0xb6b35f374d54108b2092d843bb35ea88450fc334b264d49327c13d2a9fef8c40",
        "receiptsRoot": "0xc32b297cb7a2f4772c2eef8ffce50633bccdaf2ad35147f23a8bde408089b3b6",
        "logsBloom": "0x00000000000000000000300000000000000002000100000400000000000000000100000000000000400000000000000020000000000000000000000000000000000000010000002000000008000000000000000000000004000002000000000000001000020000000000000000000800000000000000000000000010000001808000000008000001000000040000020000000000000000000000000000000000000000000000000000000000201100002000100000000000000021000100000000000002000000000200080000000000000000000000008000000000000020800800020000200000000000080000000000100010000000000000000000000000",
        "difficulty": "0x0",
        "totalDifficulty": "0x0",
        "size": "0x3b5",
        "number": "0x3f424",
        "gasLimit": "0x1c9c380",
        "gasUsed": "0x952dd",
        "timestamp": "0x6462ce4c",
        "extraData": "0x",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "nonce": "0x0000000000000000",
        "hash": "0x62912d2013a7f3901eb77bc7e7af3db1b2320803f92abf63d963e46dd96869bd",
        "transactions": [
            "0x081a73cf6132b0f48062d80231d90c39436c274dc3e2e31ded21cbe5f253fa93"
        ],
        "uncles": []
    }
}
```

<img width="863" alt="image" src="https://github.com/0xPolygonHermez/zkevm-node/assets/1298871/84cadaf4-b5eb-4304-bc78-ab62d78b6d0c">

**Comment by jleeqn** [comment]
Hi @tclemos,

I tested this method with the same payload on different RPC endpoints such as QuickNode, Alchemy, Ankr,  Blast API, etc.
All of them return the same hash `0xa708356cc28346a6c790bb1699182a06e334a93077dfefa28c745f2e0018af87`. 
Is any difference between the zkevm-rpc and these endpoints? Thanks!

**Comment by tclemos** [comment]
@jleeqn We are working together with the partners to fix this issue, we had an issue in the past regarding the log indexes that caused the problem computing the block hashes.

For now, you can use the public endpoint to retrieve the correct information while we fix this.

this is the public URL: https://zkevm-rpc.com
