### ISSUE TITLE
debug_traceTransaction without the  tracer: 'callTracer' has responses up to 40 seconds

### ISSUE THREAD

**Issue by invocamanman** [0xPolygonHermez/zkevm-node#2164]
#### System information

zkEVM Node version: `v0.1.2-RC2`
#### Expected behaviour
Responses of the traces should be within some seconds

#### Actual behaviour
Here we have a set of transactions in internal testnet and their corresponding latency time when asking for a trace
```
block:  1
0x5a5648320cec13e74b0a8852e400156ca9c29b4809a1ba2006196513d595ca62
Execution Time trace: : 12.834s
block:  2
0x2986396fd400d87e607acbc2accbceccbea5bc4457dd16b74fd468cac4807e13
Execution Time trace: : 136.048ms
block:  3
0xa9505db7d7edd08947f12f2b1f7898148ffb43d80bcb977b78161ef14173d575
Execution Time trace: : 8.639s
block:  4
0x7e7cfa6fd8dc5053848ff6494685062765fbd220fd1d6f7ff7e1028faea34783
Execution Time trace: : 44.682s
block:  5
0x8a3c1ee0bdd74b541e6f4a765301d545943b52dfc08d167f2b54329395b786a5
Execution Time trace: : 13.093s
```
#### Steps to reproduce the behaviour
Use the `debug_traceTransaction` with both this flags activated:
```
"enableMemory": true,
"enableReturnData": true
```

**Comment by tclemos** [comment]
Ok, I will review it

**Comment by ToniRamirezM** [comment]
There are txs that take more than 2 minutes to generate the trace on the executor side.
I already proposed to generate and cache the traces, but I don't see we can improve on the node side @invocamanman
