### ISSUE TITLE
The synchronization from scratch is very slow. A mainnet snapshot image is needed.

### ISSUE THREAD

**Issue by zhangguyu6** [0xPolygonHermez/zkevm-node#2231]
# Rationale

Synchronizing from zero to the latest height takes a considerable amount of time. If there was a daily updated snapshot of the mainnet, it would reduce synchronization time and accelerate the deployment of local nodes.

# Implementation

Perhaps an AWS S3 would be sufficient.

**Comment by ARR552** [comment]
Hello, we are aware of this and we have and open PR to implement this feature
https://github.com/0xPolygonHermez/zkevm-node/pull/2171
