### ISSUE TITLE
The local node data is still different from official rpc.

### ISSUE THREAD

**Issue by ideal93** [0xPolygonHermez/zkevm-node#2248]
#### System information

zkEVM Node version: `v0.1.1-v0.1.3`
OS & Version: `OSX`
Commit hash : (if `develop`)
Network: `Mainnet`

#### Expected behaviour

Local node data can be synchronized.

#### Actual behaviour

The node data is inconsistent with the official rpc. By the way, I tried many third-party RPCs, all of which are inconsistent with the official rpc.

#### Steps to reproduce the behaviour
I'm trying to use the latest version of Node and Prover/Executor to resync all data, And I found that the 'wrong block hash'  issue #2162  still hasn't been resolved. 

The generated hash of block 831 is always consistent with the third-party RPC. 

![image](https://github.com/0xPolygonHermez/zkevm-node/assets/12667721/8a781d4f-9a6b-4255-8810-96fa0e1db7a0)
Here is my operating procedure.
```
mkdir zkevm-node
cd zkevm-node
mkdir config

ZKEVM_DIR=./zkevm
ZKEVM_CONFIG_DIR=./config/
ZKEVM_ADVANCED_CONFIG_DI=./config/
ZKEVM_NET=mainnet

curl -L https://github.com/0xPolygonHermez/zkevm-node/releases/latest/download/$ZKEVM_NET.zip > $ZKEVM_NET.zip && unzip -o $ZKEVM_NET.zip -d $ZKEVM_DIR && rm $ZKEVM_NET.zip
cp $ZKEVM_DIR/$ZKEVM_NET/example.env $ZKEVM_CONFIG_DIR/.env

# EDIT THIS env file:
nano $ZKEVM_CONFIG_DIR/.env

sudo docker-compose --env-file $ZKEVM_CONFIG_DIR/.env -f $ZKEVM_DIR/$ZKEVM_NET/docker-compose.yml up
```

```
curl --location --request POST 'http://127.0.0.1/8545' \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "method": "eth_getBlockByNumber",
  "id": 1,
  "params": [
      "0x33f", true
  ]
}'
```

```
## local node
block_hash:  0x2589dcc6781e13317d8e128bc3bb4f90a0e0be0effa6f86c4bc4a3a7f0863eef. 
## official rpc
block_hash: 0xe117ba9f0f9da37ed725ae792ab8e5665ebebd598f32816893b185a107c54616.
```

**Comment by ARR552** [comment]
Hello, thanks for reporting. We are aware of this mismatch and we working on it

**Comment by dubuqingfeng** [comment]
Are there any updates?

**Comment by agnusmor** [comment]
Hi, we are working to do a rehash of the mainnet network in the next days (couldbe the week of 11th or 18th september). When done, we will provide snapshots with the blockhash fixed

**Comment by ARR552** [comment]
The mainnet rehash has been completed. Please try again using the version v0.3.0 of the node
