### ISSUE TITLE
Incorrect mainnet.zip file

### ISSUE THREAD

**Issue by breezytm** [0xPolygonHermez/zkevm-node#2346]
#### System information

zkEVM Node version: `v0.2.1`
Network: `Mainnet`

#### Expected behaviour
Mainnet configuration environment files

#### Actual behaviour

`https://github.com/0xPolygonHermez/zkevm-node/releases/latest/download/mainnet.zip` contains `testnet` config files. 

#### Steps to reproduce the behaviour
```
curl -L https://github.com/0xPolygonHermez/zkevm-node/releases/latest/download/mainnet.zip > mainnetzip && unzip -o mainnet.zip
```

**Comment by HailD** [comment]
I think it might just be [awkwardly named](https://github.com/0xPolygonHermez/zkevm-node/blob/develop/.github/workflows/release.yml#L49-L51).
If the name of the files starts with `public.` they are from the [mainnet configs](https://github.com/0xPolygonHermez/zkevm-node/tree/develop/config/environments/mainnet). The [testnet configs](https://github.com/0xPolygonHermez/zkevm-node/tree/develop/config/environments/testnet) start with `testnet.`

Related to #2340

**Comment by ToniRamirezM** [comment]
Yes, it is just a naming issue. We will fix this naming issues ASAP.

**Comment by ToniRamirezM** [comment]
Closing this as it has been fixed in the latest pre-release. Thanks for noticing it.
