### ISSUE TITLE
Fix Storage of `LocalExitRoot` in For Batch Closed After Sequencer Restart

### ISSUE THREAD

**Issue by Psykepro** [0xPolygonHermez/zkevm-node#2441]
### Overview:
During the analysis of batches with empty `LocalExitRoot`, an issue was discovered where the `LocalExitRoot` is not updated correctly. This happens when a `WIP` (not closed) `batch` with some transactions is loaded after a `Sequencer` restart, and then closed without adding any new transactions. The sequence of events results in the `LocalExitRoot` being stored as `null`, causing inconsistency.

### Impact:
This behavior leads to the incorrect storage of the `LocalExitRoot`, which could lead to further inconsistencies and issues in the transaction processing.

### Recommended Changes:

1. **Create new `UpdateBatchL2DataAndLER` Function:**
    - Add a new function named `UpdateBatchL2DataAndLER` to the `PostgresStorage`.
    - Implement the necessary changes in this new function to handle the `LocalExitRoot`, ensuring it is updated appropriately even after a sequencer restart.

### Objective:
The primary objective of these changes is to prevent the `LocalExitRoot` from being stored as `null` when a batch is closed after a sequencer restart. By introducing the new function and making the above modifications, we can ensure the correct handling of the `LocalExitRoot` and preserve data integrity.

**Comment by louisliu2048** [comment]
we have also run into this situation, when will we solve this bug?
