### ISSUE TITLE
Blocked Sender - Address is blocked by RPC 

### ISSUE THREAD

**Issue by washbin** [0xPolygonHermez/zkevm-node#2449]
#### System information

zkEVM Node version: `v0.1.2`
OS & Version: `Linux`
Network: `Mainnet`

#### Expected behaviour
My transaction goes through

#### Actual behaviour
I get error in every transaction

#### Steps to reproduce the behaviour
Don't know exactly how this behvaiour came to be. I had not used the account for about 2 months and when I tried to use it yesterday, I was unable to make any transactions. 

#### Backtrace

````
Swapped Unsuccessfully

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"blocked sender"}}}'
````

essentially the same issue as #2241 
I also tried to change the RPC url in metamask from the default zkevm to a custom one from alchemy,
No effect so far.

**Comment by agnusmor** [comment]
Hi, which is the address you are using to send this tx?

**Comment by washbin** [comment]
contacted the support team and they fixed it, it was some autoblock issue due to seemingly malicious transactions.

**Comment by sleepfinance** [comment]
Our deployment address has been blocked for nearly 4 months now
0x92417f48333a61ddC2C957044aabb9F1977cbfBC
We hoped to deploy our launchpad on polygon zkevem instead the address go blocked, where did you find support?

**Comment by washbin** [comment]
> Our deployment address has been blocked for nearly 4 months now 0x92417f48333a61ddC2C957044aabb9F1977cbfBC We hoped to deploy our launchpad on polygon zkevem instead the address go blocked, where did you find support?

@sleepfinance  you can contact the [support team](https://support.polygon.technology) with your issue,
 apparently the accounts are blocked from performing transactions due to suspicious activity history.
