### ISSUE TITLE
Review out of counters user message to make it clear

### ISSUE THREAD

**Issue by tclemos** [0xPolygonHermez/zkevm-node#2483]
we must review the behavior and message returned when calling each of these endpoints:
- eth_estimateGas
- eth_call
- eth_sendRawTransaction

**Comment by akegaviar** [comment]
This one would really help. Took me some time figure out what's going on with `eth_call` reporting `unsigned transaction` and `eth_estimateGas` reporting `unable to apply transaction even for the highest gas limit 30000000: not enough step counters to continue the execution` when doing load testing.
