### ISSUE TITLE
I get this error repeatedly when running node

### ISSUE THREAD

**Issue by rayn316** [0xPolygonHermez/zkevm-node#2495]
#### System information

zkEVM Node version: v0.1.2
OS & Version: Linux
Commit hash : (if `develop`)
Network: Mainnet

#### Backtrace

```
2023-09-01T01:51:54.720Z	WARN	synchronizer/synchronizer.go:1104	Verified Batch: {BlockNumber:18034319 BatchNumber:650893 Aggregator:0xdA87c4a76922598Ac0272F4D9503a35071D686eA StateRoot:0x53f59376d792e7792dd34f96366c6df38bddaed71125928ffa92e42d647db0d5 TxHash:0x4a97e1952345c43b4d006d2b0bada2149614118c39211906739e60f874f9924a}	{"pid": 1, "version": "v0.1.2"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processTrustedVerifyBatches
	/src/synchronizer/synchronizer.go:1104
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processBlockRange
	/src/synchronizer/synchronizer.go:433
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocks
	/src/synchronizer/synchronizer.go:276
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:220
main.runSynchronizer
	/src/cmd/run.go:312
2023-09-01T01:51:54.720Z	ERROR	synchronizer/synchronizer.go:1105	error: stateRoot calculated and state root verified don't match in processTrustedVerifyBatches. Processing blockNumber: 650893 %!s(MISSING)	{"pid": 1, "version": "v0.1.2"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processTrustedVerifyBatches
	/src/synchronizer/synchronizer.go:1105
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processBlockRange
	/src/synchronizer/synchronizer.go:433
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocks
	/src/synchronizer/synchronizer.go:276
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:220
main.runSynchronizer
	/src/cmd/run.go:312
2023-09-01T01:51:54.720Z	ERROR	synchronizer/synchronizer.go:1111	error: stateRoot calculated and state root verified don't match in processTrustedVerifyBatches. Processing blockNumber: 650893 %!s(MISSING)	{"pid": 1, "version": "v0.1.2"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processTrustedVerifyBatches
	/src/synchronizer/synchronizer.go:1111
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processBlockRange
	/src/synchronizer/synchronizer.go:433
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocks
	/src/synchronizer/synchronizer.go:276
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:220
main.runSynchronizer
	/src/cmd/run.go:312
```
When submitting logs: please submit them as text and not screenshots.

**Comment by ARR552** [comment]
Hello @sundafa , Is you node still showing this errors or was something temporary. The problematic batch was created yesterday during the update so seems to be normal.
However, your node should recover automatically if it is well configured

**Comment by rayn316** [comment]
@ARR552 Several servers are running, one of them has an alarm at a certain height, and other nodes also have this log, but the synchronization block is running normally.
The damaged one can only be reinstalled.

**Comment by alexqrid** [comment]
Got the same error 2 days ago with zkEVM Node version: `v0.1.2`, made datadir backup and tried to update the node version, but it didn't help at all. Can't synchronize my node. May be the only way is to resync from scratch, but it takes apprroximately a week.

**Comment by rayn316** [comment]
The situation is not good now. The manually stopped nodes cannot continue to synchronize after being started, and the number of nodes encountering the same problem is increasing.
Now you can only upgrade to the latest version and try to synchronize it from scratch.

**Comment by wangjiangw** [comment]
so the solution is update to new version and resync from scratch ?

**Comment by rayn316** [comment]
Now preparing to resync.

**Comment by ARR552** [comment]
Yes, try to use the version v0.2.5 for the node and v2.1.2 for the prover

**Comment by RyanWang0811** [comment]
I have two nodes both of them have the same issue.  

```log

2023-09-05T07:46:26.274Z	ERROR	synchronizer/synchronizer.go:1105	error: stateRoot calculated and state root verified don't match in processTrustedVerifyBatches. Processing blockNumber: 650893 %!s(MISSING)	{"pid": 1, "version": "v0.1.2"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processTrustedVerifyBatches
	/src/synchronizer/synchronizer.go:1105
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).processBlockRange
	/src/synchronizer/synchronizer.go:433
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncBlocks
	/src/synchronizer/synchronizer.go:276
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:220
main.runSynchronizer
	/src/cmd/run.go:312
```

I am trying to resync the node, but it will take a long time. Any method to speed it up?

**Comment by wangjiangw** [comment]
> 

i have modify the db by rollbacking the batch_num，it seems work, now the node can sync with latest block, is it a right method to fix this issue ?

**Comment by RyanWang0811** [comment]
I found the [Notion doc](https://polygontechnology.notion.site/Mainnet-Beta-UPDATE-zkEVM-Node-version-0-3-0-or-to-0-2-5-e150867951cd46c088f6d6c03b2cb5db) from this [announcement](https://forum.polygon.technology/t/polygon-zkevm-mainnet-beta-next-update-wed-6-sep-2023-at-11-00-hrs-utc/12844), and try to follow the Notion doc bottom [reference doc](https://polygontechnology.notion.site/v0-2-5-Instructions-to-fix-the-synchronisation-problem-of-the-external-nodes-743963dd6d0a4d0b9e43970642bd9cef).
Finally, the node can sync and continue.

**Comment by rayn316** [comment]
@RyanWang0811 Thanks for your help, the docs are helpful

**Comment by ARR552** [comment]
If you want rollback to a certain point of the sync to force the synchronizer to read and process some batches again, you should execute these queries in you db withe the node stopped:
```
--CREATE INDEX IF NOT EXISTS receipt_block_num_idx ON state.receipt USING btree (block_num);
delete from state.block where block_num >= bbbbbbb
delete from state.batch where batch_num >= aaaaaaa
```
bbbbbbbb would be the block from the one you want to start the sync.
aaaaaaa would be the first batch of the sequence synced in block bbbbbbb

An example would be:
```
delete from state.block where block_num >= 18033495
delete from state.batch where batch_num >= 650804
```
