### ISSUE TITLE
failed to get batch 747535 from trusted state. Error: Invalid status code, expected: 200, found: 524

### ISSUE THREAD

**Issue by RyanWang0811** [0xPolygonHermez/zkevm-node#2534]
#### System information

zkEVM Node version: `v0.3.0`
OS & Version: `Linux (Ubuntu 20.04)`
Commit hash : `4257f3f`
Network: `Mainnet`

#### Expected behaviour

TrustedSequencerURL should be more stable and have no connection issues.

#### Actual behaviour

Get the message below and the sync speed will be slow.
```log
2023-09-12T05:34:12.194Z	WARN	synchronizer/synchronizer.go:410	failed to get batch 747535 from trusted state. Error: Invalid status code, expected: 200, found: 524	{"pid": 1, "version": "v0.3.0"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).syncTrustedState
	/src/synchronizer/synchronizer.go:410
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:252
main.runSynchronizer
	/src/cmd/run.go:305
2023-09-12T05:34:12.194Z	WARN	synchronizer/synchronizer.go:255	error syncing trusted state. Error: Invalid status code, expected: 200, found: 524	{"pid": 1, "version": "v0.3.0"}
github.com/0xPolygonHermez/zkevm-node/synchronizer.(*ClientSynchronizer).Sync
	/src/synchronizer/synchronizer.go:255
main.runSynchronizer
	/src/cmd/run.go:305

```

#### Steps to reproduce the behaviour
No. Just start the node and the issue will be produced.

**Comment by agnusmor** [comment]
Hi, this was caused by an issue in the our mainnet RPC node, we have fixed it some hours ago. This error shouldn't occur again, please confirm that now you are not having these errors

**Comment by blocknodehub** [comment]
{"level":"info","ts":1695030948.7339313,"caller":"synchronizer/synchronizer.go:252","msg":"Syncing trusted state","pid":15,"version":"v0.3.1"}
{"level":"info","ts":1695030948.7339485,"caller":"synchronizer/synchronizer.go:388","msg":"Getting trusted state info","pid":15,"version":"v0.3.1"}
{"level":"warn","ts":1695030948.943405,"caller":"synchronizer/synchronizer.go:393","msg":"error syncing trusted state. Error: Invalid status code, expected: 200, found: 503","pid":15,"version":"v0.3.1"}
{"level":"warn","ts":1695030948.943442,"caller":"synchronizer/synchronizer.go:256","msg":"error syncing trusted state. Error: Invalid status code, expected: 200, found: 503","pid":15,"version":"v0.3.1"}
