### ISSUE TITLE
get revert reason when estimating gas

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#2556]
when sending a L1 tx, and the tx fails to estimate gas, the node doesn't know why. It would be very helpful to get this info for debugging.

To do so, it needs to call `eth_call` using the correct `from`, `to` and `data`. For reference this is how I've done it manually in the past:

```bash
curl -H "Content-Type: application/json" -X POST --data '{
        "jsonrpc":"2.0",
        "method":"eth_call",            
        "params":[{                                                     
                "from": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
                "to": "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
                "data": "0x438a53990000000000000000000000000000000000000000000000000000000000000060000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb9226600000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000001ab0af114b92c845a6494cc493dc00613a5df506a2f5cdd2cf4771c0ee12490d600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000064e5d5ac00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        }, "latest"],
        "id":1
}' http://localhost:8545
```

**Comment by tclemos** [comment]
I've tested the request provided in the issue and it doesn't revert.
I've tried it on zkEVM and Goerli using estimateGas and call, but none reverted.

here is the code in the estimate gas that reacts to a revert:
https://github.com/0xPolygonHermez/zkevm-node/blob/ee35f0687a583d4f3928a1bdc06131abe1991485/state/transaction.go#L1127-L1132

here is the next code that redirects the revert code to the caller:
https://github.com/0xPolygonHermez/zkevm-node/blob/ee35f0687a583d4f3928a1bdc06131abe1991485/state/transaction.go#L1146-L1149

and finally here is the code in the RPC that handles the revert:
https://github.com/0xPolygonHermez/zkevm-node/blob/ee35f0687a583d4f3928a1bdc06131abe1991485/jsonrpc/endpoints_eth.go#L189-L192

**Comment by arnaubennassar** [comment]
the `curl` request provided is just example on how to use `eth_call`.  Just copy/pasted it from my terminal history, not sure what to expect as an answer. Just to give more details, what I try to suggest:

1. If a tx reverts when estiamting gas:
2. gETH doesn't return revert reason in this case
3. But if calling `eth_call` with the same content of the tx, the revert reason is returned

**Comment by tclemos** [comment]
I thought we were talking about how the RPC was handling reverts.
Now I see it's related to the `EthTxManager`, when a component wants to add a new TX and it gets reverted while estimating gas inside of the `AddTx` method:
https://github.com/0xPolygonHermez/zkevm-node/blob/dfa0a23ed2aba17a09a17b5b652a2005d7a5259f/ethtxmanager/ethtxmanager.go#L67-L68

Well, `etherman` is the lib we have today to deal with these situations and this already exposes a method to get the revert message from a tx, here is it:
https://github.com/0xPolygonHermez/zkevm-node/blob/dfa0a23ed2aba17a09a17b5b652a2005d7a5259f/etherman/etherman.go#L1126-L1127
https://github.com/0xPolygonHermez/zkevm-node/blob/dfa0a23ed2aba17a09a17b5b652a2005d7a5259f/test/operations/wait.go#L103-L104

The revert message is not needed at this moment for the `EthTxManager` to work properly and the data provided in the TX is generated by the caller.

The `EthTxManager` handle reverts after a tx is added and needs to be monitored, but not at this point which is still being "controled" by the caller.

My suggestion is that the caller, in our case the `Sequencer` or `Aggregator` could react to the error returned by the `EthTxManager` in a way to identify if the revert message is needed, and then call the `etherman` library to get it.

**Comment by arnaubennassar** [comment]
> My suggestion is that the caller, in our case the Sequencer or Aggregator could react to the error returned by the EthTxManager in a way to identify if the revert message is needed, and then call the etherman library to get it.

Thtat would do the trick. Although, IMO, it would be better for the EthTxMan to do this, as a way to have a more detailed error. The EthTxMan is being used in a bunch of places (sequencer, aggregator, and more to come), it would be painful for everyone to have to implement the same error handling. Anyway, what you suggest is already orders of magnitude better than what we have now, and I'd be happy with that

**Comment by tclemos** [comment]
> > My suggestion is that the caller, in our case the Sequencer or Aggregator could react to the error returned by the EthTxManager in a way to identify if the revert message is needed, and then call the etherman library to get it.
> 
> Thtat would do the trick. Although, IMO, it would be better for the EthTxMan to do this, as a way to have a more detailed error. The EthTxMan is being used in a bunch of places (sequencer, aggregator, and more to come), it would be painful for everyone to have to implement the same error handling. Anyway, what you suggest is already orders of magnitude better than what we have now, and I'd be happy with that

For me it's a matter of a evaluating the trade-offs. Adding this to `EthTxManager` means "obligating" all the calls to the `Add` method to pay this price in case of an error or adding a complex rule to understand when to pay the price. in the other hand letting it out allows the caller decide what to do, and each one can decide what's best for each use case controled by them.

For me both solutions work fine, but letting it for the caller allow them to have more "control" about what's being executed on chain and how to handle in case of a problem, and as a bonus we avoid to add more complexity to the `EthTxManager` which is already a critical and complex component, of course adding this might not be too complex, but I understand it is adding one more "thing" to the cake and it opens a precedent to more things in the future.

I'm closing the issue, if you think we need to continue to discuss the topic, please reopen it and I'll be glad to help!
