### ISSUE TITLE
PUSH0 not working on mainnet

### ISSUE THREAD

**Issue by SKYBITDev3** [0xPolygonHermez/zkevm-node#2566]
Network: Mainnet

Polygon annouced that `PUSH0` will be working on mainnet from 2023-09-11: [Polygon zkEVM: Dragon Fruit Upgrade (with New Opcode) Coming to Mainnet Beta](https://polygon.technology/blog/polygon-zkevm-dragon-fruit-upgrade-with-new-opcode-coming-to-mainnet-beta)

I tried to deploy a contract with and got this error:

> ProviderError: unable to apply transaction even for the highest gas limit 30000000: invalid opcode

`PUSH0` works fine on zkEVM testnet. But is `PUSH0` actually working now on mainnet?

**Comment by krlosMata** [comment]
- Dragon Fruit upgrade has been scheduled on mainnet but it has not been executed.
  - The upgrade transaction has been scheduled on 2023-08-31 (it has been more than 10 days), but the upgrade has not been executed yet. Meaning that Dragon fruit is not available on mainnet
  - it will be available very soon xD

**Comment by SKYBITDev3** [comment]
OK thank you, I and others are waiting eagerly.

**Comment by krlosMata** [comment]
upgrade has been done in mainnet.
`PUSH0` is now supported xD
