### ISSUE TITLE
Batch `finalized` tag

### ISSUE THREAD

**Issue by krlosMata** [0xPolygonHermez/zkevm-node#2619]
# Rationale
- Add `finalized` tag in RPC batch related queries (ex: `zkevm_verifiedBatchNumber`)
- The meaning of this tag is that a batch has been included in a ethereum baloc that has been finalized in L1 (2 epochs) 

# Implementation
- use eth L1 RPC calls to know whare a block has been finalized in Eth2.0 PoS and set properly the new tag proposed `finalized`

**Comment by tclemos** [comment]
talking with the team, we ended up with some different ways to identify what would it be the correct response for each tag.

I'll list here what makes sense to me, so we can start the discussion about it, if everyone agrees, I'll update the PR to match these rules.

### PREMISE: 
for all the examples below we will assume the following network state:
- We have a total of `6 batches`, with batch numbers from `0 to 5` respectively, 

- batch state:
  - batches `0 and 1` are already `virtualized` and `verified`
  - batches `2 and 3` are already `virtualized` but `not verified`
  - batch `4` is `closed`, but `not virtualized or verified`
  - batch `5` is `open`

- batch commitment:
  - virtualization:
    - batches `0, 1, and 2` were `virtualized` in a `finalized` block on `Ethereum`
    - batch `3` was `virtualized` in a `not finalized` block on `Ethereum`
  - verification:
    - batch `0` was `verified` in a `finalized` block on `Ethereum`
    - batch `1` was `verified` in a `not finalized` block on `Ethereum`

Examples:
- `earliest:` always batch 0
- `latest:` last batch in the trusted state, in this case, it is batch 5
- `pending:` last batch virtualized in a block that has been finalized but not verified yet, in this case, it is batch 2
- `safe:` last batch virtualized in a block that has been finalized and verified in a block that was not finalized yet, in this case, it is batch 1
- `finalized:` last batch virtualized and verified in a block that has been finalized, in this case, it is batch 0

**Comment by krlosMata** [comment]
I like it !!
I propose a small change to match Ethereum tags:
- `earliest`: agree
- `latest`: last trusted batch closed but not `virtualized` yet (in this case is `4`) (I think `latest` in Ethereum gives the last closed block)
- `pending`:  last batch in the trusted state, in this case, it is batch 5
- `safe`: last virtualized (do not care about Ethereum block finalization), in this case batch 3
- `finalized`: agree

The reasoning behind this is that in virtualized blocks you still can not do any withdrawal from L2 to L1, so it less critical than having a batch verified & finalized

**Comment by tclemos** [comment]
To focus on withdrawal and to keep it simple I suggest:

- `earliest:` always batch 0
- `latest:` last batch closed in the trusted state
- `pending:` last batch `verified` in a block that is `not safe or finalized` on `Ethereum`
- `safe:` last batch `verified` in a block that is `safe` on `Ethereum`
- `finalized:` last batch `verified` in a block that has been `finalized` on `Ethereum`

I didn't mention the `Batch numbers`, because in the `premise` I didn't define the `Ethereum safe block commitment`, but if we agree on this, I can update the example with it.

With this definition, we completely forget about the virtualized and completely focus on the verification following `Ethereum block commitment` and assume this as the `Batch verification commitment`.

**Comment by tclemos** [comment]
After internal discussions, we ended up with the following definition for each tag:

- `earliest:` always batch 0
- `latest:` last batch closed in the trusted state
- `pending:` last batch in the trusted state
- `safe:` last batch verified in a block that is safe on Ethereum
- `finalized:` last batch verified in a block that has been finalized on Ethereum

Also, the endpoint `zkevm_batchNumber` will be updated to match the new `latest` definition.
