### ISSUE TITLE
The sync module hangs due to inconsistent status of trustedState

### ISSUE THREAD

**Issue by scf0220** [0xPolygonHermez/zkevm-node#2890]
in syncTrustedState func
 Step 1 :  update L2Data for  batch[0] ;  [link](https://github.com/0xPolygonHermez/zkevm-node/blob/5576e50b42f264881aec06c83502f246c53f9e19/synchronizer/synchronizer.go#L989)
 Step 2 :  processAndStoreTxs  ; [link](https://github.com/0xPolygonHermez/zkevm-node/blob/5576e50b42f264881aec06c83502f246c53f9e19/synchronizer/synchronizer.go#L1004)
 Step 3 : update trustedState.lastStateRoot ; [link](https://github.com/0xPolygonHermez/zkevm-node/blob/5576e50b42f264881aec06c83502f246c53f9e19/synchronizer/synchronizer.go#L611)

RootCause：If the second step fails, the first step should not be updated.

The problem is: if the first step is updated but the third step is not updated, then the status of trustStated will be inconsistent (for example, the current stateRoot should be the execution result of the first five transactions, but because the third step has not been executed, stateRoot is still is the execution result of the first 4 transactions), it will cause the final stateRoot to be wrong.

**Comment by ARR552** [comment]
Hi, thank you for checking the code. As I said in the PR comment, there isn't any inconsistency because variables are reset in line 378 and 379 if there is any error
