### ISSUE TITLE
Etrog: add info and exit roots to l2 block RPC responses 

### ISSUE THREAD

**Issue by ARR552** [0xPolygonHermez/zkevm-node#2930]
The bridge needs a way to retrieve the globalExitRoot (also mainnetExitRoot + rollupExitRoot) for each l2Block.
At least this field should be added but maybe there other fields such as localExitRoot that make sense to add as well

**Comment by tclemos** [comment]
reopenning to add: 
- MainnetExitRoot
- RollupExitRoot
