### ISSUE TITLE
Executions Reverting at ZKFAIR

### ISSUE THREAD

**Issue by eliteuzer** [0xPolygonHermez/zkevm-node#3005]
Transactions getting reverted and cancelled at zkfair,

Platform: Windows 11.

txn id: https://scan.zkfair.io/tx/0x4031fe405e7ef162fd313bce85b8e98d249bdf03054288eb14846c165671c648

![zkfair github](https://github.com/0xPolygonHermez/zkevm-node/assets/27822181/6b7b56f9-215b-44d2-98aa-5760501c64d9)

![zkfair github2](https://github.com/0xPolygonHermez/zkevm-node/assets/27822181/467cb7da-edaf-4cd1-a220-ebe7e7de1f40)

Firstly the txn shows Awaiting internal transactions for reason, then its gets reverted.

**Comment by eduadiez** [comment]
you should report it directly to them, we do not manage this network

**Comment by eliteuzer** [comment]
Ok, thanks
