### ISSUE TITLE
eth_getLogs api behavior different to default ETH API

### ISSUE THREAD

**Issue by louisliu2048** [0xPolygonHermez/zkevm-node#3015]
#### System information

zkEVM Node version: `v0.0.X-RCXX`
OS & Version: `Windows/Linux/OSX`
Commit hash : (if `develop`)
Network: `Mainnet/Testnet`

The default ETH_GetLogs Api param for `fromBlock` is "latest", but in zkevm, the default value is zero
#### Expected behaviour
<img width="987" alt="image" src="https://github.com/0xPolygonHermez/zkevm-node/assets/35095310/8d4a95f7-6877-4980-ba79-c5e982bfb6df">

#### Actual behaviour
<img width="937" alt="image" src="https://github.com/0xPolygonHermez/zkevm-node/assets/35095310/cb6550bf-9fd6-4182-84dd-d195f4276f8b">

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by obynonwane** [comment]
This issue has been fixed, It was part of v0.5.0 milestone  for testnet, you may have to  update your node version i.e start running the cardona testnet. The upcoming release for mainnet will have this fix as well.
