### ISSUE TITLE
eth_getLogs RPC method not working with blockHash param

### ISSUE THREAD

**Issue by MCarlomagno** [0xPolygonHermez/zkevm-node#3136]
#### System information

zkEVM Node version: `-`
OS & Version: `OSX`
Commit hash : `-`
Network: `Mainnet & Testnet`

#### Expected behaviour

When calling eth_getLogs RPC method (in both testnet and main) using blockHash as param, it should return the logs for the specified block.
```sh
curl --request POST \
     --url https://rpc.public.zkevm-test.net \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_getLogs",
  "params": [
    {
      "blockHash": "0x222e0638d8dd943994f99834d921cadf903697cf0e6d2a79e4b7ea60586ce476"
    }
  ]
}
'
```

#### Actual behaviour
When we call the previously described query it returns:
```sh
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"logs are limited to a 10000 block range"}}
```
#### Steps to reproduce the behaviour

Go to any terminal and call

```sh
curl --request POST \
     --url https://rpc.public.zkevm-test.net \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_getLogs",
  "params": [
    {
      "blockHash": "0x222e0638d8dd943994f99834d921cadf903697cf0e6d2a79e4b7ea60586ce476"
    }
  ]
}
'
```

#### Backtrace

```sh
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"logs are limited to a 10000 block range"}}
```

**Comment by tclemos** [comment]
Hey @MCarlomagno thanks for sharing this, we already fixed this issue and it will be available in the next release, this is the PR fixing it: https://github.com/0xPolygonHermez/zkevm-node/pull/3124
