### ISSUE TITLE
When a L1 reorg happens, the L1InfoTree cache is not updated

### ISSUE THREAD

**Issue by joanestebanr** [0xPolygonHermez/zkevm-node#3200]
#### System information

zkEVM Node version: `v0.5.3`
Network: `Testnet`

#### Expected behaviour
When a reorg is produced the L1InfoTree cache need to be updated 

#### Actual behaviour
When a reorg is produced the L1InfoTree cache keep the same producing a situation where new leaf are not able to be added

#### Backtrace

```
error: mismatched leaf count: 1194, expected: 1195
```

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by LinkRiver-Vitor** [comment]
Hey @joanestebanr (maybe @agnusmor can shed some light too)

I just synced snapshots from Polygons official docs:
```
https://zkevm-mai.s3.eu-west-1.amazonaws.com/mainnet-pooldb.sql.gz (65MB)
https://zkevm-mai.s3.eu-west-1.amazonaws.com/mainnet-statedb.sql.gz (6GB)
https://zkevm-mai.s3.eu-west-1.amazonaws.com/mainnet-hashdb.sql.gz (160GB)
```

Now I'm getting the same error as you did. Would you happen to direct me to some sort of solution? Re-syncing from scratch took already so long...

I would appreciated a lot, thanks!
