### ISSUE TITLE
Requesting `eth_gasPrice` method returns failure

### ISSUE THREAD

**Issue by rayn316** [0xPolygonHermez/zkevm-node#3417]
#### System information

zkEVM Node version: v0.6.1
OS & Version: Linux
Commit hash : (if `develop`)
Network: cardona

#### Expected behaviour
curl --location --request POST 'http://127.0.0.1:31881' \
--header 'Content-Type: application/json' \
--data-raw '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":1}'

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"failed to get gas price from sequencer node"}}

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by vinitran** [comment]
me too, 
``
curl 0.0.0.0:8545 \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}'

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"failed to get gas price from sequencer node"}}% 
``

**Comment by Antiquedavidsauce27** [comment]
Hello users, do you have any issue with your wallet and Have you Rectificate your wallet due to the KYC verification process in accordance with the new KYC Registration agreement. As a result,we regret to inform you that all unverified accounts with their associated assets will be frozen effective immediately

**Comment by rayn316** [comment]
> Hello users, do you have any issue with your wallet and Have you Rectificate your wallet due to the KYC verification process in accordance with the new KYC Registration agreement. As a result,we regret to inform you that all unverified accounts with their associated assets will be frozen effective immediately

Whether to reply to an error or not, the solution content has nothing to do with the bug.

**Comment by rayn316** [comment]
> me too, `` curl 0.0.0.0:8545 -X POST -H "Content-Type: application/json" --data '{"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}'
> 
> {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"failed to get gas price from sequencer node"}}% ``

It seems that using the latest configuration of `v0.6.1 cardona.zip` can return to normal, you can try it and see
