### ISSUE TITLE
Wrong URL in cardona release artifacts

### ISSUE THREAD

**Issue by joanestebanr** [0xPolygonHermez/zkevm-node#3429]
#### System information

zkEVM Node version: `v0.6.1`
Network: `Cardona`

The config file `RPC.SequencerNodeURI` is pointing to `https://rpc.devnet.zkevm-rpc.com` that is not Cardona RPC. 
It should be empty, and then is going to ask to SMC that will point to `https://rpc.cardona.zkevm-rpc.com/`

**Comment by agnusmor** [comment]
Really we need to assign empty value for RPC.SequencerNodeURI, doing this it will read the URL from the SC (as the Synchornizer does)
