### ISSUE TITLE
RPC seems to be keeping db connections open and getting stuck

### ISSUE THREAD

**Issue by tclemos** [0xPolygonHermez/zkevm-node#3628]
We faced some issues with some RPC nodes not being able to handle requests that required a db connection to state-db, and it looks like some of the connections are not getting closed properly; we need to investigate and understand better what's happening. 

We suspect this happened to the first RPCs that started and received the most requests. We have increased the number of connections to the DB, which helped avoid the problem, but we must find the source of it.

**Comment by 0xyjk** [comment]
https://github.com/0xPolygonHermez/zkevm-node/issues/3516
i also met this issue, not sure if it's caused by this

**Comment by giskook** [comment]
met the same situation, seems because the executor takes too long.
