### ISSUE TITLE
[Aggregator] Recursive proof not eligible to be verified: not containing complete sequences

### ISSUE THREAD

**Issue by DNK90** [0xPolygonHermez/zkevm-node#3703]
Hi team,

I am running zkevm on my own network.

I got the following error when aggregator trying to verify final proof that does not match with the sequence data. 

```
Recursive proof 189-189 not eligible to be verified: not containing complete sequences
```

It occurred when a sequence contains more than 1 batch. 

I've checked the sequence sender and there is not any limitation 1 batch within a sequence. 
https://github.com/0xPolygonHermez/zkevm-node/blob/develop/sequencesender/sequencesender.go#L280

While aggregator only get 1 virtual batch every time regardless of the sequence.
https://github.com/0xPolygonHermez/zkevm-node/blob/develop/aggregator/batch.go#L178

Usually, all of the sequences contain only 1 batch. however, when there is 1 sequence contains more than 1 batch. This error occurred and it is stuck here forever.

<img width="545" alt="image" src="https://github.com/0xPolygonHermez/zkevm-node/assets/3262116/bbfc85a3-71ac-49b5-b040-e263bd18313a">

Please help me how to solve this issue, thank you

**Comment by amitOodles** [comment]
@DNK90 what is the solution to the above ? I am also facing same issue on my aggregator.

**Comment by amitOodles** [comment]
@agnusmor @ToniRamirezM Can you please have a look - 

I am facing a similar issue on my ZkEVM set up. The aggregator stops sending verifyBatches transactions and i get logs similar to these -

```
zkevm-aggregator  | 2024-07-30T13:51:22.283Z	INFO	aggregator/aggregator.go:481	Recursive proof 358-371 not eligible to be verified: not containing complete sequences	{"pid": 1, "version": "3ac85397"}
```

Here are the details of the state.monitored_txs table
```
state_db=# select id, nonce from state.monitored_txs where owner = 'sequencer' order by nonce desc limit 5;
            id            | nonce 
--------------------------+-------
 sequence-from-395-to-395 |   314
 sequence-from-394-to-394 |   313
 sequence-from-393-to-393 |   312
 sequence-from-358-to-392 |   311
 sequence-from-357-to-357 |   310
 
 For aggregator, the last rows are
 state_db=# select id, nonce from state.monitored_txs where owner = 'aggregator' order by nonce desc limit 5;
          id           | nonce 
-----------------------+-------
 proof-from-356-to-357 |   297
 proof-from-355-to-355 |   296
 proof-from-354-to-354 |   295
 proof-from-353-to-353 |   294
 proof-from-352-to-352 |   293
 ```
 
And since the sequencer sent the tx with nonce 311 i.e. the one containing multiple batches, the aggregator is not adding to the monitored txs table and not sending any txs to L1.

ZkEVM node version - v 0.6.0

**Comment by DNK90** [comment]
Hi @amitOodles the root cause of this is aggregator cannot merge the sequences properly.  Previously, I met this issue when I commented out some codes related to blob transactions which is not supported in our chain. Which start from this line:
https://github.com/0xPolygonHermez/zkevm-node/blob/develop/aggregator/aggregator.go#L212
And it led to the function `tryAggregateBatchProofs` was not called.

**Comment by amitOodles** [comment]
@DNK90 @agnusmor the issue i am facing is that when the sequencer submits multiple batches in a single transaction, the aggregator is not able to generate quickly and hence there is a delay between the sequencer txs and aggregator txs.

Here is more data in continuation with the last data i submitted in prevous comment

```
state_db=# select id, nonce, created_at from state.monitored_txs where owner = 'aggregator' and nonce > 296 order by nonce limit 10;
          id           | nonce |          created_at           
-----------------------+-------+-------------------------------
 proof-from-356-to-357 |   297 | 2024-07-30 13:05:09.100469+00
 proof-from-358-to-392 |   298 | 2024-07-30 14:50:09.564765+00
 proof-from-393-to-393 |   299 | 2024-07-30 14:54:20.31068+00
 proof-from-394-to-394 |   300 | 2024-07-30 14:58:31.152984+00
 proof-from-395-to-395 |   301 | 2024-07-30 15:02:43.082568+00
 proof-from-396-to-396 |   302 | 2024-07-30 15:07:03.740841+00
 proof-from-397-to-397 |   303 | 2024-07-30 15:11:14.48992+00
 proof-from-398-to-398 |   304 | 2024-07-30 15:15:30.301357+00
 proof-from-399-to-399 |   305 | 2024-07-30 15:22:21.432722+00
 proof-from-400-to-400 |   306 | 2024-07-30 15:26:32.131562+00
(10 rows)

state_db=# select id, nonce, created_at from state.monitored_txs where owner = 'sequencer' and nonce > 310 order by nonce limit 10;
            id            | nonce |          created_at           
--------------------------+-------+-------------------------------
 sequence-from-358-to-392 |   311 | 2024-07-30 13:08:25.813147+00
 sequence-from-393-to-393 |   312 | 2024-07-30 13:11:42.792438+00
 sequence-from-394-to-394 |   313 | 2024-07-30 13:16:52.193222+00
 sequence-from-395-to-395 |   314 | 2024-07-30 13:22:17.310704+00
 sequence-from-396-to-396 |   315 | 2024-07-30 13:27:29.162819+00
 sequence-from-397-to-397 |   316 | 2024-07-30 13:32:04.466917+00
 sequence-from-398-to-398 |   317 | 2024-07-30 13:37:29.249214+00
 sequence-from-399-to-399 |   318 | 2024-07-30 13:41:41.104006+00
 sequence-from-400-to-400 |   319 | 2024-07-30 13:47:03.29106+00
 sequence-from-401-to-401 |   320 | 2024-07-30 13:52:05.117783+00
```

From the above you can see that the aggregator submitted the proofs for the batches 358-392 almost 2 hours after sequencer submitted those batches. How can i reduce the delay between aggregator and sequencer ?

**Comment by DNK90** [comment]
@amitOodles with mine, I set it as 5 minutes of creating new batch. It takes around 5-6 minutes to do the aggregate or generate final batch proof.
