### ISSUE TITLE
Trusted sequencer should be aware of L2 reorgs

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#796]
Sequencer should be notified if a L2 reorg happens (trusted state != virtual state) as it may have WIP sequences being built on top of a wrong state.

- [ ] Synchronizer notifies when a reorg is detected
- [ ] Trusted sequencer halts operation
- [ ] Synchronizer notifies when the reorg has been re-processed (this can take a while as it could imply processing a few batches)
- [ ] Trusted sequencer will most likely need to drop the WIP sequences and then resume operation

**Comment by tclemos** [comment]
@arnaubennassar how is the state of this task after your `Sequencer` refactoring?
