### ISSUE TITLE
RPC should execute txs before adding into the pool

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#816]
- Do not add if txs exceed max gas or ZK counters
- Store ZK counters and used gas in the pool

**Comment by arnaubennassar** [comment]
This should be done once the `cnt_*` from the prover are working https://github.com/0xPolygonHermez/zkevm-prover/issues/13

**Comment by ToniRamirezM** [comment]
Duplicated in #1146
