### ISSUE TITLE
state.CheckSupersetBatchTransactions should compare txHash field and not tx.Hash() method

### ISSUE THREAD

**Issue by ToniRamirezM** [0xPolygonHermez/zkevm-node#902]
It looks like the value in txHash is not correct, so for the moment the code will compare against tx.Hash()

The corresponding test has been commented so it does not get executed. This should be uncommented once the tx hash is properly calculated.

https://github.com/0xPolygonHermez/zkevm-node/pull/901/files#diff-ad95c17c31b539a3e385a23d86bbecf4d8a925ba6679aec2e66b5202ba4c4f81R797

**Comment by arnaubennassar** [comment]
Blocked by the executor. This should be done once the executor properly calculate the tx hash
