### ISSUE TITLE
Review running node local / production doc

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygonHermez/zkevm-node#909]

**Comment by AwaitFuture** [comment]
Second this request; things Ive noticed trying to push things together:

1. the docker containers required to run locally pull from a private docker repo; this can be replaced with either requiring you build each piece locally or releasing the docker images.

2. make init-network calls code thats completely commented out; following and uncommenting code leads to calls on functions for package `etherman` which dont seem to exist

**Comment by arnaubennassar** [comment]
@AwaitFuture thanks for the report. As you have figured out, both the doc and the code it's outdated right now as we've been through a massive refactor recently. We're working hard on stabilizing everything.

It will take a bit to reach a fully functional node, but we will work on updating both the docs and scripts to be able to run it with the features that are currently working ASAP

**Comment by AwaitFuture** [comment]
Thank you for the explanation @arnaubennassar ; if theres anything I can do to help please let me know. in the mean time Ive been working backwards, finding which commits in the past still seem to work together and rebuilding containers against those more stable commits.

is there a reason etherman is getting a major refactor? In my brief overview of it, it seems like its typechain for go; you hand it some ABIs, and it generates some bindings for you to call in another script.

**Comment by arnaubennassar** [comment]
A few months ago we had massive breaking changes:

- Smart contract updates to enable instant finality, and the introduction of the "trusted sequencer" role
- Switch from a Go implementation of the EVM and Merkletree to the one done in https://github.com/0xPolygonHermez/zkevm-prover to ensure consistency of what is done off-chain vs the ZeroKnowledge proofs that are sent to L1. Right now we're integrating with this new EVM that is not feature complete yet: https://github.com/0xPolygonHermez/zkevm-prover/issues/13

So the current status is:

- Docs are outdated
- Tons of features broken as we can't execute unsigned transactions yet (estimate gas, view methods, ...)

The bulk of the job is done, we're mostly facing integration issues at the moment. Probably on Monday we'll have the Docker images open, and the docs updated with a propper explanation of what is working and what not.
