### ISSUE TITLE
How to run a local node?

### ISSUE THREAD

**Issue by samlior** [0xPolygonHermez/zkevm-node#922]
I followed this [guide](https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/running_local.md) to run a local node, 
but when I run `make run`, I get this error:
```
Pulling zkevm-mock-l1-network (hermeznetwork/geth-zkevm-contracts@sha256:419cf8c488d5cd099d1ffb5722613375c5392bdcda7a3c5ae2801d498fe49af8)...
ERROR: pull access denied for hermeznetwork/geth-zkevm-contracts, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [run] Error 1
```

**Comment by arnaubennassar** [comment]
Hi @samlior thanks for reporting this. We're on the process of opening the Docker images, right now they are private. This should be done in the next days.

Of course you could build the different images manually if you're in a hurry.

Closing the issue in favour of #909

**Comment by AUQIB92** [comment]
I am still facing the same issue, Did you open Docker images
