### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by TalDerei** [0xPolygonHermez/zkevm-node#924]
"It's recommended that the prover is run on a separate instance, as it has important hardware requirements. On the other hand, all the other components can run on a single instance."

What are the estimated hardware requirements to run the zkEVM node components on one instance, and the prover on another? This is missing from the docs. 

A response on this issue would be greatly appreciated from the engineering team ~

**Comment by arnaubennassar** [comment]
gm @TalDerei, I'm afraid we don't have numbers yet, but here are some considerations:

- The node it's relatively light. All the team members have been running it on laptops without trouble. However, we still have to test this under stress and obviously the more transactions the network has processed historically, the more disk it will be needed
- The executor and prover are treated as an external dependency, and this should be documented on its own repo https://github.com/0xPolygonHermez/zkevm-prover

**Comment by TalDerei** [comment]
Right makes sense @arnaubennassar! 

I have the cloud compute resources to run the prover. Can you tell me the rough vCPUs/memory required on the VM so the prover doesn't fail to run. Thanks!

**Comment by krakhit** [comment]
Any updates on the hardware requirements?

**Comment by xavier-romero** [comment]
The node could be run all together on any commodity hardware, the question here is the network activity and mainly other components required by the node to work.
As many node components require an [Executor](https://github.com/0xPolygonHermez/zkevm-prover) (`zkProver` in Executor mode) to work, a good practice is to have a dedicated Executor for every node component that requires it, so, for each of these components I'd suggest not less that 32GB RAM (it depends on what is going to be executed on the Executor and how many executions is going to receive concurrently). For reference, right now 64GB is enough for the zkEVM Testnet and Mainnet Executors.
That would be the suggestion:

- RPC + Executor, 64GB RAM + 32 cores
- Sequencer + Executor, 32GB RAM + 16cores
- Synchronizer + Executor, 32GB RAM + 16 cores
- WS + Executor, 32GB RAM + 16 cores
- Remaining node components all together, 8GB RAM + 8 cores


If you don't expect much activity you could share the Executor for all of the components.

- Executor, 64GB RAM + 32 cores
- Node components all together, 16GB RAM + 16 cores

If we are talking about the [Prover](https://github.com/0xPolygonHermez/zkevm-prover), it is the `zkProver` in Prover mode (not Executor mode), then we need a lot of RAM, currently they're working fine with 768GB RAM but you should be able to run them with 512GB sacrificing OS buffers and cache. The more CPUs it has the fastest it's going to prove, but nothing required, you could have just 1 core and sit for hours until a prove is done :-)
For reference here, AWS `r6*.24xlarge` (128vcpus AMD or Intel) brings a proof in a bit less than 4 min.


Part from all this you will need databases. Again it all depends on the network load, if you can afford isolated databases for node and statedb (prover) it would be the best approach.
