### ISSUE TITLE
missing docker files

### ISSUE THREAD

**Issue by TalDerei** [0xPolygonHermez/zkevm-node#930]
I notice the docker hub is missing some docker images like zkEVM-mock-l1-network defined in the zkEVM node's Makefile:

<img width="499" alt="Screen Shot 2022-07-25 at 6 05 58 AM" src="https://user-images.githubusercontent.com/70081547/180784824-79549fc5-2cf1-4536-b2b6-25eb7bb95e6f.png">

And therefore "make run" fails to fetch the image. 

<img width="1246" alt="Screen Shot 2022-07-25 at 6 06 11 AM" src="https://user-images.githubusercontent.com/70081547/180785051-ed00dfae-064c-4688-9f43-30a3e83a1e06.png">

Can I get access to the images in the hermez organization for testing purposes? Otherwise I can't seem to run the repo in a local/production environment.

**Comment by arnaubennassar** [comment]
The images are not public yet, as they are not ready to use. If you want to build them yourself, you can do it.
All the images can be build through using different repos from this organization. In this case https://github.com/0xPolygonHermez/zkevm-contracts

**Comment by TalDerei** [comment]
I see, the zkEVM contracts contains instructions to spin up a geth node similiar to the zkEVM-mock-l1-network image. Can the rest of the images zkEVM-sequencer/zkEVM-aggregator/zkEVM-json-rpc/zkEVM-sync/etc. be built under here:
https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/production-setup.md?

Thanks! @arnaubennassar
