### ISSUE TITLE
Update name

### ISSUE THREAD

**Issue by TalDerei** [0xPolygonHermez/zkevm-node#934]
**FIX 1:** "hermez-geth1.3:latest" under the zkevm-contracts repo is renamed to "hermeznetwork/geth-zkevm-contracts:latest" when running the deploy-docker.sh script. Readme should reflect the change.

**Comment by TalDerei** [comment]
Apologies for the multiple edits, was revising on the go. Above issue represents the current open question. Thanks!

**Comment by arnaubennassar** [comment]
If this issue is related to contracts repo, please open it there

**Comment by arnaubennassar** [comment]
Closing as this is not related to this repo
