### ISSUE TITLE
zkevm-node setup issue

### ISSUE THREAD

**Issue by TalDerei** [0xPolygonHermez/zkevm-node#935]
I'm following the docs described here: https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/production-setup.md

I successfully pulled the image "docker pull hermeznetwork/zkevm-node:develop" from the dockerhub.

During the zkEVM-Node Setup, I'm trying to execute this command "docker run --rm hermeznetwork/zkevm-node:develop sh -c "./zkevm-node encryptKey --pk=<account private key> --pw=<password to encrypt> --output=./keystore; cat ./keystore/*" > acc.keystore". 

I changed the pk to one of the private keys from "deploy_output.json" file when setting up the geth L1 chain, described in the zkevm-contracts repo. I show that below:

<img width="870" alt="Screen Shot 2022-07-25 at 3 41 36 PM" src="https://user-images.githubusercontent.com/70081547/180886350-7a61f0cc-e40e-4a3e-94ee-81c73d3b3ceb.png">

...
There are two problems:
**1.** When running the command, it says './zkevm-node' folder is not found, when it's clearly defined (currently empty). Not sure what's going on there.

<img width="1437" alt="Screen Shot 2022-07-25 at 3 44 04 PM" src="https://user-images.githubusercontent.com/70081547/180886785-04cc814f-8381-4674-98af-797c98dd63f4.png">

**2.** The config file to create the config.toml file takes you to a bad link: https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/config/config.debug.toml

Need some assistance setting up the node manually, since I can't run in the other way defined here (since I don't have access to some of the docker images!): https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/running_local.md

Thanks for the help!

**Comment by arnaubennassar** [comment]
> 1. When running the command, it says './zkevm-node' folder is not found, when it's clearly defined (currently empty). Not sure what's going on there.

Try with `/app/zkevm-node` instead of `./zkevm-node`

> 2. The config file to create the config.toml file takes you to a bad link: https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/config/config.debug.toml

https://github.com/0xPolygonHermez/zkevm-node/blob/develop/config/config.local.toml

Be aware that right now the node is quite broken. We're facing integration and stability issues, as well as outdated docs. We expect to release `v0.0.1` in the following weeks with most of this issues fixed

**Comment by TalDerei** [comment]
Why did you mark as closed? This is still an open issue for me.

Can you please let me know what command you ran above? This command does not work for me: sudo docker run --rm hermeznetwork/zkevm-node:develop sh -c "./zkevm-node encryptKey --pk=0x8b50b058927083657735612dcfef8544c7056f1f728c5f1b5f5296ce2e068a4d --pw=passphrase --output=./keystore; cat ./keystore/*" > acc.keystore

Thanks!

**Comment by TalDerei** [comment]
makes sense, I was looking at the go files before as well!

In terms of the next command, any idea why it's not picking up the 'register' command?

<img width="1438" alt="Screen Shot 2022-07-26 at 9 59 32 AM" src="https://user-images.githubusercontent.com/70081547/181066467-449dd0f0-1195-47e8-b5b3-b55471e3a98b.png">
