### ISSUE TITLE
sequencer setup missing function 

### ISSUE THREAD

**Issue by TalDerei** [0xPolygonHermez/zkevm-node#942]
In terms of the next command "**sudo docker run --rm -v /$HOME/zkevm-node/config.toml:/app/config.toml hermeznetwork/zkevm-node:develop sh -c "/app/zkevm-node register --cfg=/app/config.toml --network=internaltestnet --y 0x9CF6bA663FC99B8B8B3c0F4ACbcDbE9c35976769**"

when trying to register the Ethereum account as a sequencer, it's not picking up the 'register' command?

<img width="1438" alt="181066467-449dd0f0-1195-47e8-b5b3-b55471e3a98b" src="https://user-images.githubusercontent.com/70081547/181091559-bf27cc2b-e572-4554-a99e-6375a3718a4f.png">

Looking at the go code, it's missing the register function.

<img width="607" alt="Screen Shot 2022-07-26 at 12 07 23 PM" src="https://user-images.githubusercontent.com/70081547/181091899-60e01c39-071f-43b4-9b6f-fb49c17ead22.png">

What command can I run to continue setting up the zkevm-node? Thanks! @arnaubennassar

**Comment by arnaubennassar** [comment]
The register function doesn't exist anymore. It was removed in the latest smart contract updates
